version: '3.9'
services:
  web:
    build:
      context: .
      target: nextjs_server
      args:
        BUILD_ENV: ${BUILD_ENV}
        BUILD_ID: ${BUILD_ID}
        GRAPHQL_ENDPOINT: ${NEXT_PUBLIC_GRAPHQL_ENDPOINT:?Missing graphql endpoint}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN}
    restart: always
    ports:
      - ${PORT:-8080}:3000
