const colorNames = [
  'surface',
  'subsurface',

  'primary1',
  'primary2',
  'primary3',
  'primary4',
  'primary5',
  'primary6',
  'primary7',
  'primary8',
  'primary9',
  'primary10',
  'primary11',
  'primary12',
  'primaryA1',
  'primaryA2',
  'primaryA3',
  'primaryA4',
  'primaryA5',
  'primaryA6',
  'primaryA7',
  'primaryA8',
  'primaryA9',
  'primaryA10',
  'primaryA11',
  'primaryA12',
  'danger1',
  'danger2',
  'danger3',
  'danger4',
  'danger5',
  'danger6',
  'danger7',
  'danger8',
  'danger9',
  'danger10',
  'danger11',
  'danger12',
  'dangerA1',
  'dangerA2',
  'dangerA3',
  'dangerA4',
  'dangerA5',
  'dangerA6',
  'dangerA7',
  'dangerA8',
  'dangerA9',
  'dangerA10',
  'dangerA11',
  'dangerA12',
  'success1',
  'success2',
  'success3',
  'success4',
  'success5',
  'success6',
  'success7',
  'success8',
  'success9',
  'success10',
  'success11',
  'success12',
  'successA1',
  'successA2',
  'successA3',
  'successA4',
  'successA5',
  'successA6',
  'successA7',
  'successA8',
  'successA9',
  'successA10',
  'successA11',
  'successA12',
  'warning1',
  'warning2',
  'warning3',
  'warning4',
  'warning5',
  'warning6',
  'warning7',
  'warning8',
  'warning9',
  'warning10',
  'warning11',
  'warning12',
  'warningA1',
  'warningA2',
  'warningA3',
  'warningA4',
  'warningA5',
  'warningA6',
  'warningA7',
  'warningA8',
  'warningA9',
  'warningA10',
  'warningA11',
  'warningA12',
  'neutral1',
  'neutral2',
  'neutral3',
  'neutral4',
  'neutral5',
  'neutral6',
  'neutral7',
  'neutral8',
  'neutral9',
  'neutral10',
  'neutral11',
  'neutral12',
  'neutralA1',
  'neutralA2',
  'neutralA3',
  'neutralA4',
  'neutralA5',
  'neutralA6',
  'neutralA7',
  'neutralA8',
  'neutralA9',
  'neutralA10',
  'neutralA11',
  'neutralA12',
]

const colorMap = {}
colorNames.forEach((name) => {
  colorMap[name] = `var(--colors-${name})`
})

module.exports = {
  colors: colorMap,
  textColors: {
    hi: colorMap.neutral12,
    lo: colorMap.neutral11,
    xlo: colorMap.neutral8,
    primaryLo: colorMap.primary11,
    primaryHi: colorMap.primary12,
    dangerLo: colorMap.danger11,
    dangerHi: colorMap.danger12,
    successLo: colorMap.success11,
    successHi: colorMap.success12,
    warningLo: colorMap.warning11,
    warningHi: colorMap.warning12,
  },
}
